version: '3'
services:
  pkfilemanager-server:
    build: ./server
    container_name: pkfilemanager-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    command: npm start
    image: pkfilemanager-server:latest
