version: '3'
services:
  pkfilemanager-db:
    container_name: pkfilemanager-db
    image: mongo:latest
    env_file:
      - .env
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_ADMINPASSWORD
    volumes:
      - db-data:/data/db

  pkfilemanager-server:
    build: .
    container_name: pkfilemanager-server
    ports:
      - "3000:3000"
    depends_on:
      - pkfilemanager-db
    links:
      - pkfilemanager-db
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: npm start
    volumes:
      - npm-cache:/root/.npm
    image: pkfilemanager-server:latest

volumes:
  npm-cache:
    name: npm-cache
  db-data:
    name: db-data
